sudo: required

services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t frontend .

script:
    - docker run -e CI=true frontend npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-495717134924"
    bucket_path: "docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
